### ISSUE TITLE
Out of box fail: Imported as maven project to Eclipse Oxygen

### ISSUE THREAD

**Issue by zaszlo** [interseroh/demo-gwt-springboot#7]
Seems like it doesn't find Address interface, etc. 353 Java Problem items reported in Eclipse after maven import and installing the prompted gwt related plugin and eclipse restart and maven update, clean... Maybe I'm still missing something?

**Comment by lofidewanto** [comment]
You have to generate the Interfaces with Maven generate-sources first. We use KissMDA to generate the Java interfaces.

**Comment by lofidewanto** [comment]
KissMDA: https://github.com/crowdcode-de/kissmda

**Comment by zaszlo** [comment]
As the target audience for this demo project is newbies it wouldn't hurt to see a step by step description including this, like: After download slow down, don't try to just run it before doing this/these steps: 
- download this KissMDA and run it on this project like so... 

Thanks! 👍

**Comment by zaszlo** [comment]
Ok got it, just had to type mvn compile, so:

After download slow down, don't try to just run it before compiling, run: `mvn compile` first.
Then launch it from `com.lofidewanto.demo.server` package's DemoGwtSpringbootApplication.java as Java Application or if you have STS in your Eclipse, launch as Spring Boot Application.

**Comment by zaszlo** [comment]
I thought I got it working, but even after a half an hour I still get only the google preloader on http://localhost:9014/demogwt/ . Maybe missing a step?
On the console nothing shows that something would have went wrong:
```
2018-04-11 11:46:12.038  INFO 8264 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 9014 (http)
2018-04-11 11:46:12.045  INFO 8264 --- [           main] c.l.d.s.DemoGwtSpringbootApplication     : Started DemoGwtSpringbootApplication in 8.579 seconds (JVM running for 9.259)
2018-04-11 11:49:41.681  INFO 8264 --- [nio-9014-exec-5] o.a.c.c.C.[.[localhost].[/demogwt]       : Initializing Spring FrameworkServlet 'dispatcherServlet'
2018-04-11 11:49:41.681  INFO 8264 --- [nio-9014-exec-5] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization started
2018-04-11 11:49:41.729  INFO 8264 --- [nio-9014-exec-5] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 48 ms
```
Launching it by cmdline w/ maven `mvn -P development gwt:run-codeserver`, on http://127.0.0.1:9876/demogwt/ I get only this after more than 10 minutes:
```
demogwt (GWT Code Server)
This module hasn't been compiled yet.

Output Files
(From the last successful compile.)

clear.cache.gif
demogwt.nocache.js
demogwt.recompile.nocache.js
```
In the cmdline it regularly fetches new lines like:
```
[INFO] 09:09:41.997 [org.eclipse.jetty.server.session.HashSessionManager@40db6335Timer] DEBUG org.eclipse.jetty.server.session - Scavenging sessions at 1523437781997
[INFO] 09:10:11.998 [org.eclipse.jetty.server.session.HashSessionManager@40db6335Timer] DEBUG org.eclipse.jetty.server.session - Scavenging sessions at 1523437811998
```
I can't believe that a demo project complies for more than half an hour with 16 GB RAM and i5 CPU. Closed it after an hour.

Disclaimer: I couldn't follow the facets configuration on Eclipse Neon, what's the equivalent for simply Web in Eclipse?

**Comment by lofidewanto** [comment]
To run the webapp you need to do following (see the detail at https://github.com/interseroh/demo-gwt-springboot#run-the-webapp-for-development):

- Server part: you need to run the Spring Boot app: run the class **DemoGwtSpringbootApplication**
- Client part (GWT):  you need to run the GWT transpiler: **mvn gwt:run-codeserver**
- Open your browser and use: http://localhost:9014/demogwt

That's it.

**Comment by lofidewanto** [comment]
I checked with STS (Spring Tool Suite) 3.9.3, everything is very fast. The first loading of http://localhost:9014/demogwt takes a bit because GWT compiles the whole Java to JavaScript. But afterwards GWT compiles very fast (incremental) because it's only compiles the changes classes. You just need to change the Java code and save it. Afterwards reload the address in the web browser, that's it.

**Comment by lofidewanto** [comment]
At the moment I'm working on GWT Boot (gwtboot) just like Spring Boot: https://github.com/gwtboot

With this GWT Boot you will be able to start your GWT project very easily just like using Spring Boot. 

Example of using GWT Boot with Spring Boot:
https://github.com/gwtboot/gwt-boot-samples/tree/master/gwt-boot-sample-basic-with-spring-boot

It's still under development but it will make the whole thing easier.

**Comment by zaszlo** [comment]
Thank you, for following up, it works now. The difference that I did this time is only to call `mvn gwt:run-codeserver` instead of `mvn -P development gwt:run-codeserver`. Now the overlaying complies message has showed up in the browser and after a while the demo app came in, yey! Afterwards, now tried with the development arguments and now that also works... Maybe I wasn't waiting to launch this gwt compiler and entered to the browser right after booting up spring.

I'm new to GWT, will look into that GWT Boot, thanks for pointing it out!

... by the way what ui styling are you using in this demo, it looks good, but doesn't seem to be neither bootstrap nor material... nor Kendo. In my first GWT project I should use Kendo UI, would you have any words on that?

**Comment by lofidewanto** [comment]
With the -P development you call the Profile development from Maven. I defined the profile will only compiles Java to JS for Safari and Chrome, maybe you are using Firefox?

I'm using Gwtbootstrap3 for design: https://github.com/gwtbootstrap3/gwtbootstrap3
... With my own Bootstrap design.

Here you have a list of all available UI frameworks for GWT: https://github.com/gwtboot/gwt-boot-modules/blob/master/README.md

For new projects I would use Domino UI... It's not finished yet but looks very good. Ask the community here: https://gitter.im/domino-gwt/domino-ui

They have example and so on.
